### ISSUE TITLE
Change down arrow on keyboard to the word done

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/newwwspring.cc#117]
Is the down arrow clear enough? Done is close to normal keyboards

**Comment by samclaridge** [comment]
I played around with done, but without tabbing arrows on the right to balance it out it just looked kinda weird. The genera inspiration for the arrow was from iOS.




Open to changing though :)

**Comment by jbaxleyiii** [comment]
@samclaridge I'm good to hold for further testing. Anecdotally I've seen a few people miss it and not know how to close it down but :shrugs:
