### ISSUE TITLE
Back button on iOS

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/newwwspring.cc#120]
It shows up in the browser. But, not on iOS:

![screenshot 2015-08-06 16 02 12](https://cloud.githubusercontent.com/assets/816517/9122082/88f3963e-3c54-11e5-8136-8a788db47380.png)

**Comment by johnthepink** [comment]
This appears to be an issue with `-webkit-overflow-scrolling: touch`. That property causes iOS to calculate `z-index` differently. Good article [here](http://benfrain.com/z-index-stacking-contexts-experimental-css-and-ios-safari/).

When I remove `-webkit-overflow-scrolling: touch` from `.breadcrumb`'s parent elements (`.scrollable`, `.panel`, `.global-nav-offset`) then the back arrow re-appears. Also, setting it to `-webkit-overflow-scrolling; auto` works.

It seems like the best practice is to apply the scrolling attribute to just the element with the overflow that will be scrolling, instead of cascading them down the DOM. This also fixes the problem.

So maybe we just get more conservative with that attribute? Or, we could re-work the way our breadcrumbs function. But, it seems like throwing webkit scrolling around could cause problems for our z-indexes long-term.

Thoughts @jbaxleyiii?

**Comment by jbaxleyiii** [comment]
@johnthepink that sounds great. Nice research into it. I think its definitely better practice to be more conservative with the overflow scrolling. Does `-webkit-overflow-scrolling: auto` give you smooth scrolling in iOS? If so it could be a good standard to move to.

Lets transition the touch to auto and be more conservative with the overflows.

Oh css...

**Comment by johnthepink** [comment]
@jbaxleyiii I think auto stops scrolling immediately. Whereas touch gives you the inertia scrolling. 

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

So it sounds like being conservative is the way to go.

**Comment by jbaxleyiii** [comment]
@johnthepink agreed, inertia scrolling is a must
