### ISSUE TITLE
Giving history wording and formatting

### ISSUE THREAD

**Issue by benwiley** [NewSpring/newwwspring.cc#207]
@jbaxleyiii @johnthepink 

Peoples should be people's.  Maybe use this wording:

`Because of your generosity, we are able to continue telling stories of the greatness of Jesus and seeing people's lives changed.`

Also should always show two decimals

**Comment by dcs619** [comment]
I would only expect it to show two decimals if there was a decimal place; my normal gifts don't have a decimal value.

**Comment by johnthepink** [comment]
Good catch! How to English?

**Comment by dcs619** [comment]
Engrish!

**Comment by dcs619** [comment]
@jbaxleyiii bump 

![](https://media.giphy.com/media/13SO1BotDzqqk/giphy.gif)
