### ISSUE TITLE
Turn on LDAP

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/newwwspring.cc#78]
Can we do this with digital ocean easy?

@delianides any thoughts / experience

**Comment by delianides** [comment]
I honestly don't know. Part of the transition to AWS was to enable IT to remove the Cisco Firewall which is how we are authenticating now. I'd need to know more information about the new Fortigate software to see if a tunnel can be established. 

Honestly, An easier solution would be to run staff/vol beta on AWS (I can help) which would allow the instances to exist within our VPN.

**Comment by jbaxleyiii** [comment]
@delianides lets spin up 4 ec2 instances within our cluster next week. One that is pretty beefy and 3 lean ones. We can talk specs. Then we can try to deploy to them and leave DO

**Comment by delianides** [comment]
:) I know that was hard for you @jbaxleyiii
